use crate::domain::LicenseError;
use crate::{builder::builder::Builder, 
            builder::director::Director,         
            services::encapsulate::EncapsulateService,        
            builder::license_builder::LicenseBuilder,        
            services::product_manager::ProductIdentifier,      
            services::license_manager::LicenseIdentifier,
            services::hardware_manager::Hwid
            };
use crate::input::{ask_path, ask_option};

use chrono::{Duration, Timelike, Utc};

use rusqlite::{Result};
//use rusqlite::{Connection};   

use std::env;
use std::io::{self, Write};

// Mensaje inicial de Secenly
fn show_menu() {
    println!("=====================================================================");
    println!("======================== WELCOME TO SECENLY! ========================");
    println!("=====================================================================\n");
    println!("Select an option:");
    println!("1. Generate a new license");
    println!("2. Delete an existing license");
    println!("3. Modify a license");
    println!("4. List all licenses");
    println!("5. Read an existing license from an archive");
    println!("0. Exit");
}

// Función principal del programa. Recibe por línea de comandos la función a
// realizar en la herramienta (0-5)
pub fn run() {
    loop {
        let args: Vec<String> = env::args().collect();

        let opt = if args.len() > 1 {
            args[1].trim().to_string()
        } else {
            show_menu();
            io::stdout().flush().unwrap();

            let mut input = String::new();
            io::stdin().read_line(&mut input).unwrap();
            input.trim().to_string()
        };

        match opt.as_str() {
            "1" | "create" => {
                if let Err(e) = create_license() {
                    eprintln!("Error: {}", e);
                }
            }
            "2" | "delete" => {
                if let Err(e) = delete_license() {
                    eprintln!("Error: {}", e);
                }
            }
            "3" | "modify" => {
                if let Err(e) = modify_license() {
                    eprintln!("Error: {}", e);
                }
            }
            "4" | "list" => {
                if let Err(e) = list_licenses() {
                    eprintln!("Error: {}", e);
                }
            }
            "5" | "read" => {
                if let Err(e) = read_license() {
                    eprintln!("Error: {}", e);
                }
            }
            "0" | "exit" => {
                println!("Closing Secenly...");
                break;
            }
            _ => {
                println!("Invalid option, try again.");
                continue; 
            }
        }

        // Evita que, si pasaron argumentos por CLI, se repita en bucle
        if args.len() > 1 {
            break;
        }
    }
}

/*pub fn connect_db() -> Result<Connection> {
    let conn = Connection::open("secenly.db")?;  
    Ok(conn)
}*/

pub fn create_license() -> Result<(), LicenseError> {
    // Obtención de rutas para almacenar la semilla, licencia y donde se
    // encuentra el certificado y la clave privada.
    let seed_path = ask_path(&"seed will be save".to_string());
    let license_dir = ask_path(&"license will be save".to_string());
    let license_path = license_dir.join("license.der");
    let cert_path = ask_path(&"certificate is locate (with his name)".to_string());
    let key_path = ask_path(&"private key is locate (with his name)".to_string());

    let product_identifier = ProductIdentifier::initialize(
        &seed_path, Hwid::obtain_hwid()?)?;
    let license_identifier = LicenseIdentifier::initialize(
        &product_identifier.get_product_id())?;

    // Obtención de la duración de la licencia
    let duration = ask_option(
        "Select the duration of the license:\n\
         1) 1 day\n2) 7 days\n3) 1 month\n4) 3 months\n5) 6 months\n6) 1 year",
        |option| match option {
            1 => Some(Duration::days(1)),
            2 => Some(Duration::days(7)),
            3 => Some(Duration::days(30)),
            4 => Some(Duration::days(90)),
            5 => Some(Duration::days(180)),
            6 => Some(Duration::days(365)),
            _ => None,
        },
    );

    // Obtención de la expiración de la licencia
    let expiration = Utc::now()
        .with_nanosecond(0)
        .unwrap()
        + duration;

    // Obtención del intervalo de latidos
    let heartbeat = ask_option(
        "Select heartbeat interval:\n\
         1) 15 seconds\n2) 30 seconds\n3) 1 minute\n4) 5 minutes\n5) 15 minutes\n6) 1 hour",
        |option| match option {
            1 => Some(15),
            2 => Some(30),
            3 => Some(60),
            4 => Some(300),
            5 => Some(900),
            6 => Some(3600),
            _ => None,
        },
    );
    
    let notes = String::from("License generated by CLI");

    let mut license_builder = LicenseBuilder::default();

    // Construcción de la licencia
    Director::construct_license(&mut license_builder, 
        license_identifier.get_license_id(), 
        expiration, 
        heartbeat, 
        notes);

    let license = license_builder.build();

    EncapsulateService::encapsulate_license(license, 
        &license_path, 
        &cert_path, 
        &key_path);

    Ok(())
}

pub fn delete_license() -> Result<()> {
    println!("Seleccione la licencia que desea eliminar");
    // MOSTRAR LAS LICENCIAS ASOCIADAS A ESE USUARIO

    Ok(())
}

pub fn modify_license() -> Result<()> {
    println!("Seleccione la licencia que desea modificar");
    // MOSTRAR LAS LICENCIAS DE LA BBDD CUYO HWID CORRESPONDA AL DEL USUARIO
    // Mas bien, muestra los softwares que cuentan con licencia el usuario

    Ok(())
}

pub fn read_license() -> Result<()> {
    //let data = read("license.lic").unwrap();
    //println!("RAW DER bytes: {:02X?}", data);
    //let license: License = rasn::der::decode(&data).unwrap();
    Ok(())
}

pub fn list_licenses() -> Result<()> {
    println!("Licencias arraigadas a su usuario:");
    // MOSTRAR LAS LICENCIAS DE LA BBDD CUYO HWID CORRESPONDA AL DEL USUARIO
    Ok(())
}